run:
  timeout: 5m

linters-settings:
  gocyclo:
    min-complexity: 20
  errcheck:
    check-type-assertions: true
    check-blank: false

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - contextcheck

issues:
  exclude-dirs:
    - test
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
